#!/usr/bin/perl
use v5.24;

my $answer = int(1 + rand 100);
my $tip = $ENV{TIP} // 1;
while (1) {
	my $input = <STDIN>;
	chomp($input);
	
#	if ($input == ''|| $input == "quit" || $input == "exit") {
	if ($input =~/quit|exit|\A\s*\z/i) {
		last;
	}
		
	elsif ($input == $answer) {
		print "You are correct!\n";
		last;
	}
	elsif ($input < $answer) {
		print "Too low\n";
	}
	elsif ($input > $answer) {
		print "Too high\n";
	}
	 {
		print "Answer is $answer\n" if ($tip);
	}
}

