#!/usr/bin/perl

use v5.24;

my $pi = 3.141592654;
say "input the radius";
chomp(my $radius = <STDIN>);
if ($radius < 0) {
	$radius = 0;
}
say "circumference of the circle of radius of "
	.$radius." is ".$radius * 2 * $pi;

