#!/usr/bin/perl
use utf8;
use v5.24;
use warnings;
#use diagnostics;

#say "hello world\"";
#say "\x{2668}";
#say "\N{SNOWMAN}";
#say 'hello world\n';
#say "hello worldi\x7fi";
#
#say "hello" x 12;
#
#say "12dsf" * '12.3';

my $alpha = chr( 0x03c9 );
print "$alpha\n";

my @fred = qw(eating rocks is wrong);
my $fred = "right";
say "this is $fred[3]";
say "this is ${fred}[3]";
say "this is $fred"."[3]";
say "this is $fred\[3]\n";

my @rocks = qw/ bedrock slate lava /;
my $rock = "";
foreach $rock(@rocks) {
	$rock = "\t$rock";
	$rock .= "\n";
}
say "the rocks are:", @rocks;
say "the control value is:", $rock;

say "input lines:";
my @lines = <STDIN>;
@lines = reverse @lines;
print @lines;

chomp(my $line = <STDIN>);
say $line;
say chomp($line);
